### ISSUE TITLE
custom stream text inputs jump around (autosort?) when typing in them

### ISSUE THREAD

**Issue by sean1138** [chromakode/streamwall#10] opened 2020-06-24 19:04 UTC
Is there a way around this behavior that you could point me to?  I'm good with html & css but pretty weak with javascript.

https://files.catbox.moe/1kdrjt.mp4

The fix i have in mind would be to keep the custom streams input list order static and add a button to sort them after the user has finished typing in the title/name of a stream.

Another idea that i probably don't have the skills to make happen would be to pull the title from the URL of the first text input and autofill the second text input - still allowing the user to change it of course.

**Comment by chromakode** [comment] 2020-06-25 00:32
This was caused by a change I introduced yesterday to sort the internal storage of streams. The custom streams list keeps track of which input you're typing in by index position, but renders based on this internal store, so the sorting was causing it to lose track of which stream you were editing. I've changed it to not reorder the internal data store, and instead sort when displaying the list in the control window.

Fixed in https://github.com/chromakode/streamwall/commit/d55ab32f0f5b7be0cd9d70956a14470914b87afd. Thanks for the report!

**Closed by chromakode** 2020-06-25 00:32 UTC
